version: "2"

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"

python:
  setup_py_install: true
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py